package org.example.sfdc.pages.acccounts;

/**
 * Class containing enum.
 */
public enum AccountFormField {
    ACCOUNT_NAME,
    ACCOUNT_TYPE,
    ACCOUNT_WEBSITE,
    ACCOUNT_DESCRIPTION,
    ACCOUNT_PHONE,
    ACCOUNT_INDUSTRY,
    ACCOUNT_EMPLOYEES,
    ACCOUNT_BILLING_STREET,
    ACCOUNT_BILLING_CITY,
    ACCOUNT_BILLING_ZIP,
    ACCOUNT_BILLING_STATE,
    ACCOUNT_BILLING_COUNTRY,
    ACCOUNT_SHIPPING_STREET,
    ACCOUNT_SHIPPING_CITY,
    ACCOUNT_SHIPPING_ZIP,
    ACCOUNT_SHIPPING_STATE,
    ACCOUNT_SHIPPING_COUNTRY
}
